#!/usr/bin/env python
import os
import sys
import subprocess


def start():
    os.environ["DJANGO_SETTINGS_MODULE"] = "data_storage.settings"
    env = os.environ.get("ENV", "dev")
    cmd = 'gunicorn -w 6 -b 0.0.0.0:8000 data_storage.wsgi --timeout 120'
    if env == "dev":
        cmd += " --reload"
    subprocess.call(cmd, shell=True)

    
if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "data_storage.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError:
        try:
            import django
        except ImportError:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )
        raise
    execute_from_command_line(sys.argv)
